module

public meta import Lean.Elab.Command
public meta import Lean.Widget.UserWidget
public meta import ImportGraph.Imports.RequiredModules
public meta import ImportGraph.Imports.ImportGraph
public meta import ImportGraph.Graph.TransitiveClosure
meta import all Lean.ExtraModUses
public meta import Lake.CLI.Shake
import all Lake.CLI.Shake
import all Lean.Elab.Command

/-!
# Shake utilities

This file extends the (currently private) `shake` API, and includes some theory on the module system.

`Shake` records relations of the form

- module `i` needs module `j` at availability `k`

and uses this information to modify existing `import` blocks.

This information arises from usages of declarations and metaprograms from `j` within module `i`, and is recorded in environment extensions. (`shake` also takes into account `-- shake: <annotation>`  comments.)

## Theory

Abstractly, we model import hierarchies participating in the module system as a set of objects (modules) together with generating relations of the form `j [m, p⟩ i` between them denoting `import` statements.

Specifically, let `m ∈ {0,1}` denote the **phase**, i.e. whether the import is `meta` (`1`) or not (`0`), and `p ∈ {0,1,2}` denote the **visibility**, i.e. whether the import is private (unadorned) (`0`), `public` (`1`), or `import all` (`2`). (We use digits here for conciseness of notation in future expressions.) Together, we call `k = (m,p)` the **availability**.

We have `j [k⟩ i` if `i` directly imports `j` at availability `k`. For example, `j [0,1⟩ i` with `m = 0`, `p = 1` means that `i` has a direct import of `public import <j>`. (Mnemonic: information flows left to right, along the arrow.)

These are not the objects shake records. Instead, shake records similar relations `j ⟦m, p⟫ i` where `p` is restricted to `{0,1}`. For convenience, we'll allow ourselves to coerce `{0,1,2}` to `{0,1}` by the map `mod 2`—`0` and `1` are preserved, and `2` is sent down to `0`. (Reason: `import all` does not make the public scope available.)

Note crucially that `j ⟦k⟫ i` is not mutually exclusive with `j ⟦k'⟫ i`. Each arrow `j ⟦k⟫ i` for each `k` is present or not independently of every other `j ⟦k'⟫ i`. (The hom set is not enriched in `Avail`, but in the powerset of `Avail`.)

Shake introduces `Needs`, and calls the availability `NeedsKind`.
```
/-- Logically, a map `NeedsKind → Set ModuleIdx`, or `Set Import`. -/
structure Needs where
  pub : Bitset
  priv : Bitset
  metaPub : Bitset
  metaPriv : Bitset
```
This is *not* a collection of arrows `j ⟦k⟫ i`. Rather, by itself, it's an "abstract slice": a collection of "prearrows" `j ⟦k⟫ ·` with no concrete or necessarily existing codomain. We use it as such at various points.

Note that at every point we are talking only about the public scope of `j`, and the availability `k : NeedsKind` describes the way it is used or needed within `i`. It may be needed only at a private position, or at a public position, or at either of those visibilities in the meta phase. We do not (currently?) record or represent usages of `j`'s private scope (even though these may arise from `import all`).

### Transitivity

However, shake also records a set of nonreflexively transitively closed dependencies for each module, `transDeps : Array Needs`. This uses `Needs`, but might more accurately be considered to describe a "Has" relation. In this context, we *do* actually want to consider this to be a collection of arrows, with the array index corresponding to the `ModuleIdx` of the codomain. That is, `transDeps[i]` records the arrows `j ⟦k⟫ i` generated by direct import relations `j [k⟩ i`.

What do we mean by "generated" here? We use the following "derivation rules", which describe how (transitive) import availabilities propagate through direct imports:

- `j [m,p⟩ i`  ⟹  `j ⟦m,p⟫ i`
- `j' ⟦m,1⟫ j [m',p⟩ i`  ⟹  `j' ⟦m ∨ m', p⟫ i`
- `j' ⟦m,0⟫ j [0,2⟩ i`  ⟹  `j' ⟦m,0⟫ i`

(Note that nontrivial coercion to `0` in the `p = 2` case is taking place, as described above.)

These may be simplified notationally by leaving the domain and codomain implicit:

- `[m,p⟩`  ⟹  `⟦m,p⟫`
- `⟦m,1⟫[m',p⟩`  ⟹  `⟦m ∨ m', p⟫`
- `⟦m,0⟫[0,2⟩`  ⟹  `⟦m,0⟫`

and we will occasionally do so in the future.

Note that `⟦_⟫` is by default *irreflexive*.

The last two rules give us a concrete notion of "composition" between `⟦k⟫` on the left and `[k⟩` on the right.

Note that, with some reasoning, we can include a composition rule between two transitive relations `⟦_⟫`'s without breaking anything, which is essentially a copy of the second rule:

- `⟦m,1⟫⟦m',p⟫`  ⟹  `⟦m ∨ m', p⟫`

This does not introduce any new relations not already obtained by considering `[⟩`, but rules 1 and 2 together are not sufficient to produce the arrows produced in rule 3, and there is no way to generate these arrows by considering `⟦_⟫`'s alone, as it depends on the `import all`/`p = 2` information stored only in `[_⟩` relations.

We write `𝓘` for the "mathematical version" of `transDeps`: the import hierarchy considered together with all of its `⟦_⟫` arrows.

Note that given a prearrow `f` of the form `j ⟦k⟫ ·` or a direct prearrow `j [k⟩ ·`, we can make sense of the composition(s) `𝓘 ≫ f`. This is the set of all prearrows we get by composing all arrows in `𝓘` with `f` when composition is possible. Note that a set of prearrows is a `Needs`. We may similarly extend this sense of composition to the case where `f` is a set of prearrows instead of just one (i.e. where `f : Needs`), and denote by `𝓘 ≫ f` the set of all possible compositions we can form.

The **transitive closure** of a set of prearrows `ν` (nu) relative to some `𝓘` is then `𝓘[ν] := ν ∪ (𝓘 ≫ ν)`. It's possible to prove that `𝓘[·]` is idempotent.

Here we also take a moment to define a "rooted slice" `(ν, i)` which should be considered to be a set of arrows `j ⟦k⟫ i` (which may or may not exist in `𝓘`). We also define the "concrete slice" `𝓘 ↓ i` which is the rooted slice of all arrows `j ⟦k⟫ i` in `𝓘`.

### Operations on `𝓘`

#### Linearizing

Note that while the process of generating `𝓘` can be thought of as for the most part producing a "has" relation among modules, it does not necessarily satisfy

- `j ⟦m,1⟫ i`  ⟹  `j ⟦m,0⟫ i`

even though if `i` has access to `j` publicly, it also has access to `j` privately. We call the process of including all of these private `⟦_,0⟫` arrows in an import hierarchy `𝓘` or slice `ν` **linearizing** the hierarchy or slice, and denote it by `ℓ` (in both situations). Note that we may split this into an operation `ℓ₀` which *replaces* every arrow `⟦m,1⟫` with its private version `⟦m,0⟫`; then `ℓx = x ∪ ℓ₀x`. This makes certain proofs convenient.

We can prove that `ℓ(𝓘[ν]) = 𝓘[ℓν]`. Note that `ℓ(𝓘)[ν] = 𝓘[ν]`, since the extra private arrows `ℓ` adds to `𝓘` cannot be composed with any of the prearrows in `ν`.

Note that `ℓ(𝓘)` preserves the transitively-closed property of `𝓘`. (This remains true even if we "regenerate" using the basis elements `[k⟩` after applying `ℓ`, which does not add any extra elements.)

Of course, `ℓ(a ∪ b) = ℓa ∪ ℓb`, and `ℓℓ = ℓ`.

Note that we could also instead "antilinearize" to attempt to have a single representative arrow for each meaningful relation, i.e. we could instead enforce

- `j ⟦m,1⟫ i`  ⟹  `¬ j ⟦m,0⟫ i`

This can make certain things more efficient.

#### Reflexifying

We mentioned that `⟦_⟫` was by default irreflexive. This does not reflect the "has" relation very well: `i` has access to its own public scope both publicly and privately. But, note, it does *not* have access to its own public scope at the meta level. So it would (only) make sense to add the arrows

- `∀ i, i ⟦0, p⟫ i`

We call this "reflexifying" an import hierarchy. We denote the operation by `r`, and the process of adding *only* `i ⟦0, 1⟫ i` as `r₁`. This is special, since `i ⟦0,1⟫ i` behaves like an identity (when it can be composed).

We will sometimes denote `i ⟦0, 1⟫ i` by `r₁(i)` and `{i ⟦0, 1⟫ i, i ⟦0, 0⟫ i}` by `r(i)`.

Note that reflexifying a transitively closed import hierarchy `𝓘` does not in general result in a transitively closed import hierarchy! Namely, the new private self-arrows may generate new private non-self arrows. This is a lot like what linearizing does, and in fact, if `tc` denotes taking the transitive closure, `tc(r(𝓘)) = ℓr(𝓘)`.

We also have `ℓr₁(𝓘) = ℓr(𝓘) = rℓ(𝓘)`.

It does not make sense to apply `r` to an abstract slice, but it *does* make sense to apply it to a rooted slice (and thereby a concrete slice `𝓘 ↓ i`): this just adds the relevant self-arrows for `i` alone.

Extending `𝓘[·]` to rooted slices in the obvious way (`𝓘[(ν,i)] := (𝓘[ν], i)`), we also have that `rℓ(𝓘[ν,i]) = 𝓘[rℓ(v,i)]`, and the above commutation relations as well.

Note that `rℓ(𝓘 ↓ i)` = `rℓ(𝓘) ↓ i`. Further, note that
`r₁(𝓘 ↓ i) = r₁(𝓘 ↓ i)₁ ∪ (𝓘 ↓ i)₀ = 𝓘[r₁(i)] ∪ (𝓘 ↓ i)₀`, with `(_)₀` denoting the private arrows. Now, `ℓr(𝓘 ↓ i) = ℓr₁(𝓘 ↓ i) = ℓ(𝓘[r₁(i)]) ∪ ℓ(𝓘 ↓ i)₀ = 𝓘[r(i)]) ∪ (𝓘 ↓ i)₀`.

#### Subsumption

A `Needs` `ν` is provided within some module `i` if `ν ⊆ rℓ(𝓘 ↓ i)`.

A `Needs` `ν` is subsumed by some other `Needs` `μ` in `𝓘` if `𝓘[ℓν] ⊆ 𝓘[ℓμ]`, which is equivalent to `ν ⊆ 𝓘[ℓμ]`. We write this as `ν ≤[𝓘] μ`.

Reducing a `Needs` `ν` to surface-level imports means finding a `Needs` `μ` such that `μ` is minimal among `Needs` which satisfy `ν ≤[𝓘] μ`. Note: this minimality requirement implies that `μ` is antilinearized. We may then interpret each prearrow in `μ` as the corresponding `import` statement.

Practically, we can do this by iterating backwards through the topological sort (by domain) of (remaining) prearrows `f` in `ν`, starting with the public non-meta availability prearrows, and steadily removing `𝓘[f] = {f} ∪ (𝓘 ≫ f)` from `ν` while recording `f`. The result will satisfy the condition we need. Note: if `𝓘` is irreflexive, we can also just remove `𝓘 ≫ f` from `ν` (being sure not to remove `𝓘 ≫ g` for `g ∈ ν` if `g` has already been removed by a prior step).

A note on the global hierarchy structure: by design, `⟦_⟫` "breaks" compositions. We cannot actually detect whether a module `i` is higher or lower in the hierarchy overall than a module `j` simply by comparing `𝓘 ↓ i` and `𝓘 ↓ j`, in general. Instead, we need to record a separate "precedes" relation `j` on each module `i`. This is not provided out of the box by shake API, but we use the same `Bitset` approach to extend `Needs`.

-/
